services:

  notification-service:
    image: 'mongo'
    container_name: notification_service_db
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: sm_notification_service_db
    volumes:
      - ./notification-service-mongo-data:/data/db
      - ./docker/mongodb/notification/initdb.d:/docker-entrypoint-initdb.d
    restart: unless-stopped
    networks:
      - social-network

  postgres:
    image: 'postgres:latest'
    container_name: postgres_db
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: sm_content_service_db
    volumes:
      - ./pg_data:/var/lib/postgresql
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    networks:
      - social-network

  user-service-db:
    image: 'postgres:latest'
    container_name: user_service_db
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: sm_user_service_db
    volumes:
      - ./user-service-pgdata:/var/lib/postgresql/user_service/data
      - ./docker/postgres/user/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    networks:
      - social-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: pgadmin_password
    depends_on:
      - postgres
      - user-service-db
    volumes:
      - ./pgadmin-data/:/var/lib/pgadmin/
      - ./docker/pgadmin/servers.json:/pgadmin4/servers.json
    restart: unless-stopped
    networks:
      - social-network

  keycloak-db:
    image: mysql:8.3.0
    container_name: keycloak-mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: keycloak_db
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: password
    volumes:
      - ./volume-data/mysql_keycloak_db:/var/lib/mysql
    networks:
      - social-network

  keycloak:
    container_name: keycloak-service
    image: quay.io/keycloak/keycloak:26.4.2
    command: ["start-dev","--import-realm"]
    environment:
      DB_VENDOR: MYSQL
      DB_ADDR: mysql
      DB_DATABASE: keycloak_db
      DB_USER: keycloak
      DB_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_IMPORT: /opt/keycloak/data/import/
      KC_EXPORT: 'true'
      KC_EXPORT_DIR: /opt/keycloak/data/export/
    ports:
      - "8100:8080"
    volumes:
      - ./docker/keycloak/realms/import:/opt/keycloak/data/import
      - ./docker/keycloak/realms/export:/opt/keycloak/data/export
    depends_on:
      - keycloak-db
    networks:
      - social-network

  zookeeper:
    image: confluentinc/cp-zookeeper:7.9.4
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 3000
    networks:
      - social-network

  kafka-broker:
    image: confluentinc/cp-kafka:7.9.4
    container_name: kafka-broker
    ports:
      - "9092:9092"
      - "29092:29092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-broker:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - social-network

  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - "8084:8080"
    depends_on:
      - kafka-broker
    environment:
      KAFKA_CLUSTERS_NAME: local
      KAFKA_CLUSTERS_BOOTSTRAPSERVERS: kafka-broker:29092
      DYNAMIC_CONFIG_ENABLED: 'true'
    networks:
      - social-network

  kafka-schema-registry:
    image: confluentinc/cp-schema-registry:8.1.0
    hostname: kafka-schema-registry
    container_name: kafka-schema-registry
    depends_on:
      - kafka-broker
    ports:
      - "8083:8081"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: kafka-schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: 'kafka-broker:29092'
      SCHEMA_REGISTRY_LISTENERS: http://kafka-schema-registry:8081
    networks:
      - social-network

  redis:
    container_name: redis
    image: redis:8.4.0-alpine
    command: redis-server /usr/local/etc/redis/redis.conf --requirepass ${REDIS_PASSWORD}
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data:/data
      - ./docker/redis/:/usr/local/etc/redis/

    restart: unless-stopped
    env_file:
      - ./.env
    networks:
      - social-network

volumes:
  postgres_data:
  keycloak_realms:

networks:
  social-network:
    driver: bridge