services:

  postgres:
    image: 'postgres:latest'
    container_name: postgres_db
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: sm_content_service_db
    volumes:
      - ./pg_data:/var/lib/postgresql
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: pgadmin_password
    depends_on:
      - postgres
    volumes:
      - ./pgadmin-data/:/var/lib/pgadmin/
    restart: unless-stopped

  keycloak-db:
    image: mysql:8.3.0
    container_name: keycloak-mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: keycloak_db
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: password
    volumes:
      - ./volume-data/mysql_keycloak_db:/var/lib/mysql

  keycloak:
    container_name: keycloak-service
    image: quay.io/keycloak/keycloak:26.4.2
    command: ["start-dev","--import-realm"]
    environment:
      DB_VENDOR: MYSQL
      DB_ADDR: mysql
      DB_DATABASE: keycloak_db
      DB_USER: keycloak
      DB_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8100:8080"
    volumes:
      - ./docker/keycloak/realms/:/opt/keycloak/data/import
    depends_on:
      - keycloak-db

volumes:
  postgres_data: